create table if not exists public.planos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  ruta_storage text not null,
  creado_el timestamptz not null default timezone('utc', now()),
  constraint planos_nombre_no_vacio
    check (char_length(btrim(nombre)) > 0),
  constraint planos_ruta_storage_no_vacia
    check (char_length(btrim(ruta_storage)) > 0),
  constraint planos_ruta_storage_unica
    unique (ruta_storage)
);

create index if not exists planos_nombre_idx
  on public.planos (nombre);

comment on table public.planos is
  'Planos SVG o imagenes base para representar zonas de la oficina.';

comment on column public.planos.ruta_storage is
  'Ruta del fichero dentro del bucket planos, por ejemplo: informatica.svg';
